require("mikowhy.plugins-setup") -- musi byc na gorze
require("mikowhy.core.options")
require("mikowhy.core.keymaps")
require("mikowhy.core.colorscheme")
require("mikowhy.plugins.comment")
require("mikowhy.plugins.nvim-tree")
require("mikowhy.plugins.lualine")
require("mikowhy.plugins.telescope")
require("mikowhy.plugins.nvim-cmp")
require("mikowhy.plugins.lsp.mason")
require("mikowhy.plugins.lsp.lspsaga")
require("mikowhy.plugins.lsp.lspconfig")
require("mikowhy.plugins.lsp.null-ls")
require("mikowhy.plugins.autopairs")
require("mikowhy.plugins.treesitter")
require("mikowhy.plugins.gitsigns")
require("mikowhy.core.osc52")
